### ISSUE TITLE
error running colab examples

### ISSUE THREAD

**Issue by renshugu** [mikonvergence/DiffusionFastForward#2]
Hello, thanks for the DIffusionFastForward course and colab examples. 
I'm getting the following error running 02-Pixel-Diffusion-colab as well as 03-Conditional-Pixel-Diffusion. Would you mind taking a look and giving me some pointers?

trainer.fit(model)

INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name  | Type                      | Params
----------------------------------------------------
0 | model | DenoisingDiffusionProcess | 56.6 M
----------------------------------------------------
56.6 M    Trainable params
0         Non-trainable params
56.6 M    Total params
226.463   Total estimated model params size (MB)
Sanity Checking:
0/? [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py](https://localhost:8080/#) in _check_dataloader_iterable(dataloader, source, trainer_fn)
    382     try:
--> 383         iter(dataloader)  # type: ignore[call-overload]
    384     except TypeError:

TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
10 frames
[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py](https://localhost:8080/#) in _check_dataloader_iterable(dataloader, source, trainer_fn)
    397                 f" `def {source.name}(self):` in your LightningModule/LightningDataModule."
    398             )
--> 399         raise TypeError(
    400             f"An invalid dataloader was returned from `{type(source.instance).__name__}.{source.name}()`."
    401             f" Found {dataloader}."

TypeError: An invalid dataloader was returned from `PixelDiffusion.val_dataloader()`. Found None.

**Comment by mikonvergence** [comment]
Hello! Thank you for bringing this up!

This error occurs due to the recent upgrade of `pytorch_lightning` to `2.0`. A quick fix is to change the installation line from `! pip install pytorch-lightning diffusers einops kornia` to
```python
! pip install pytorch-lightning==1.9.3 diffusers einops kornia
```
as that's the last compatible version.

I will probably go through the changes required for `2.0` and update the all course code accordingly in the next few days.

Please let me know if the solution above works for you (it has worked for me).
